spring:
  application:
    name: molchanova-telegram-bot

telegrambot:
  name: ${TG_NAME_GPB}
  token: ${TG_TOKEN_GPB}
  client:
    urls:
      host: http://localhost:8084/api/v1
      endpoints:
        users:
          register: /users
        accounts:
          create: /users/{id}/accounts
          get: /users/{id}/accounts
        transfers:
          create: /transfers