package ru.molchmd.minibank.frontend.telegrambot.util;

public enum ExtendedStatus {
    USER_NOT_EXIST,
    USER_ALREADY_EXIST,
    ACCOUNT_ALREADY_EXIST,
    SENDER_USER_NOT_EXIST,
    SENDER_RECIPIENT_SAME,
    SENDER_USER_ACCOUNT_NOT_EXIST,
    RECIPIENT_USER_NOT_EXIST,
    RECIPIENT_USER_ACCOUNT_NOT_EXIST,
    AMOUNT_CONVERT_NUMBER,
    AMOUNT_MORE_TWO_CHAR,
    AMOUNT_LESS_ZERO,
    AMOUNT_LESS_ALLOWED_MIN,
    AMOUNT_HIGHER_ALLOWED_MAX,
    AMOUNT_NOT_ENOUGH;
}
